version: '3.8'

services:
  web:
    build: ./web
    image: yourusername/hoteli-web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hotel_reservations
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
